### ISSUE TITLE
企業紹介文の別ページ化と同期

### ISSUE THREAD

**Issue by fumy231** [mapconcierge/www_geoten#1]
企業紹介文を別ページ(別タブ)にしてください。

情報が追加されていますので、同期をお願いします。
https://www.goga.co.jp/company/event20170421.html

イベント後にもう一回同期をお願いすると思います。
来年までログになるので、何卒よろしくお願いします。

**Comment by mapconcierge** [comment]
# MEMO
---


## イベント情報

4月21日(金)「ジオ展2017」開催のご案内

ジオビジネス関連の複数企業による共同イベントです。展示会形式で実施され、どの時間帯でもご自由に出入りできます。2016年11月に行われたジオ展より更に規模を拡大し、今回はヤフーロッジにて開催します。地図や位置情報に関するソリューションをお求めの方を始め、ジオ業界への就職を希望される学生や求職者の方も歓迎いたします。

## 開催概要
### 日時
2017年4月21日(金) 10:00-17:00
### 会場
ヤフーロッジ
東京都千代田区紀尾井町1-3 東京ガーデンテラス紀尾井町 18F
### 参加費
無料
### 主催
ジオ展運営事務局 (株式会社ゴーガ)
### お申し込み
Googleフォームよりお申し込みください。

## 出展企業
ヤフー株式会社
http://www.yahoo.co.jp/
株式会社ヴァル研究所
http://www.val.co.jp/
NTT空間情報株式会社
http://www.ntt-geospace.co.jp/
ESRIジャパン株式会社
http://www.esrij.com/
インクリメントP株式会社
http://www.incrementp.co.jp/
合同会社MIERUNE
http://www.mierune.co.jp/
株式会社ナビタイムジャパン
http://corporate.navitime.co.jp/
Pacific Spatial Solutions, LLC
http://pacificspatial.com/
株式会社コミュニケーション・プランニング
http://www.cpnet.co.jp/
マルティスープ株式会社
https://www.multisoup.co.jp/
LIFE STYLE株式会社
http://l-s.co.jp/
株式会社岩根研究所
http://www.iwane.com/
特定非営利活動法人 クライシスマッパーズ・ジャパン
http://crisismappers.jp/
首都大学東京 渡邉英徳研究室
http://labo.wtnv.jp/
株式会社ゼンリンジオインテリジェンス
http://www.zgi.co.jp/
株式会社ゴーガ
http://www.goga.co.jp/


# 出展企業紹介（50音順）

## インクリメントP株式会社
インクリメントP株式会社ではMapFanAPI、MapFanSDKを始めとした地図ソリューション販売を行っております。本展示会には法人向け地図データ製品であるMapFanDBを展示します。
カーナビゲーションにも利用される高精度な道路ネットワークデータを中心にGISシステム向けの様々なコンテンツを紹介します。

## 株式会社ヴァル研究所
「駅すぱあと路線図」は、様々なデータを駅や路線で集約し活用するニーズに対応するべく、企業や団体が保有するデータやコンテンツと自由に連携できる業界初の全国路線図APIです。
■特徴
　1.全国の鉄道路線と駅を1枚の路線図で表示、拡大縮小、スクロール可能
　2.スマートフォンでも動作が軽くスムーズな操作感を実現
　3.特定の駅にピンを立てる、路線に色をつけるなど自由な表現が可能
　4.利用者自身が保有するデータ／コンテンツと連携可能
　5.英語版の路線図や駅ナンバリングに対応

## 特定非営利活動法人 クライシスマッパーズ・ジャパン
大規模災害時にOpenStreetMapを活用して迅速に被災地の地図を作成、現場を後方支援する青山学院大学を本拠地とするボランティア団体です。とくに、発災後の様子をドローンを用いて空から空撮し、迅速に被害状況をマッピングする災害ドローン救援隊DRONEBIRD計画の詳細を展示します。

## 株式会社ゴーガ
株式会社ゴーガは、Google Mapsのプレミアパートナーとして、Google Maps API Premium Planの販売及び実装を承っております。 JAPAC Partner of the Yearも受賞した技術力とフットワークでお客様の地図活用を支援いたします。JavaScript, Python, PHPによるウェブシステム、iPhoneアプリ、Androidアプリの開発を得意としています。 そのほか、上記各社の製品販売、OpenStreetMap, MapBox, CARTOなどの活用支援を行なっています。

## 首都大学東京 渡邉英徳研究室
首都大・渡邉研では，オープンソースのJSライブラリ「Cesium」を用いたデジタルアース・コンテンツを制作しています。これまでに「ヒロシマ・アーカイブ」「震災犠牲者の行動記録」などを発表してきました。本展示では，京都大学東南アジア地域研究研究所，帝国データバンク，佐賀大学医学部との共同研究成果を紹介します。

## 株式会社　ナビタイムジャパン
ナビタイムジャパンは、ナビタイム・電通・Takramの3社で共同開発した「Round Trip Analyzer」(RTA)を出展します。RTAは、訪日外国人向けアプリ「NAVITIME for Japan Travel」利用者のGPS測位データを元に、訪日外国人旅行者の国内回遊状況を「市区町村間の移動」という単位で描画するインタラクティブなビジュアライザーです。
操作者が直感的・対話的に訪日外国人の移動実態を理解できます。

## Pacific Spatial Solutions, LLC
地理情報の活用には時間がかかる。CARTOがこの問題を解決します。スマートシティ、エリアマネージメント、ビジネスインテリジェンス、オープンデータなら、Pacific Spatial Solutionsにお任せください。そして、もう一つ強力な地図ビジネスツール AvenzaMaps。スマホに地図を取り込んで、オフラインで使えます。さらに、オリジナル地図を世界に向けて販売できます。

## マルティスープ株式会社
マルティスープ株式会社は「つくる喜び、つかう喜び」をモットーに、地図と位置・空間情報をつかいお客様の業務を効率化をはかる「iField(アイ・フィールド)」、屋内測位技術を活用したソリューション「iField indoor(アイ・フィールド インドア)]の開発・提供を行っています。本展示では、熊本県立大学での被害調査の活用事例紹介をはじめ、インフラ・工場・倉庫・病院など、様々な“現場”を可視化・効率化の支援を行った事例をご紹介いたします。

## 合同会社MIERUNE
MIERUNE地図として、OpenStreetMapを独自スタイルで提供しており、
1．低コストでの導入が可能
2．印刷などへの二次利用が可能
3．さまざまなデザインに対応
といった特徴を持っています。
今回のジオ展ではMIERUNE地図の新しいスタイルをご覧いただくとともに、OpenStreetMapやweb地図の活用、地図データの配信についてのご相談を受け付けます。また、MIERUNEは「QGIS」のスポンサーとなっています。QGISの利活用、プラグイン開発についてのご相談も承ります。

## LIFE STYLE株式会社
LIFE STYLEは、VRクリエイターエコシステムを展開するベンチャー企業です。
VRクリエイターエコシステムとは、良質なVRコンテンツをより多くのユーザーに届けるためのコミュニティです。具体的には、VRを学ぶ場・VR制作ツール・VRに特化したマッチングサービスを展開しています。VR制作ツールは、360°でその場にいるかのような体験ができるVRコンテンツを、皆様が簡単に制作・活用できる「Flic360Make」サービスとなっております。VRを体験したい方・VRのビジネス活用をお考えの方は、是非ブースまで足をお運びください。

**Comment by mapconcierge** [comment]
http://md2pdf.higty.xyz/md2html


'
<h1 id="-50-">出展企業紹介（50音順）</h1>
<h2 id="-p-">インクリメントP株式会社</h2>
<p>インクリメントP株式会社ではMapFanAPI、MapFanSDKを始めとした地図ソリューション販売を行っております。本展示会には法人向け地図データ製品であるMapFanDBを展示します。
カーナビゲーションにも利用される高精度な道路ネットワークデータを中心にGISシステム向けの様々なコンテンツを紹介します。</p>
<h2 id="-">株式会社ヴァル研究所</h2>
<p>「駅すぱあと路線図」は、様々なデータを駅や路線で集約し活用するニーズに対応するべく、企業や団体が保有するデータやコンテンツと自由に連携できる業界初の全国路線図APIです。 <br>
■特徴<br>
　1.全国の鉄道路線と駅を1枚の路線図で表示、拡大縮小、スクロール可能<br>
　2.スマートフォンでも動作が軽くスムーズな操作感を実現<br>
　3.特定の駅にピンを立てる、路線に色をつけるなど自由な表現が可能<br>
　4.利用者自身が保有するデータ／コンテンツと連携可能<br>
　5.英語版の路線図や駅ナンバリングに対応</p>

<h2 id="-">特定非営利活動法人 クライシスマッパーズ・ジャパン</h2>
<p>大規模災害時にOpenStreetMapを活用して迅速に被災地の地図を作成、現場を後方支援する青山学院大学を本拠地とするボランティア団体です。とくに、発災後の様子をドローンを用いて空から空撮し、迅速に被害状況をマッピングする災害ドローン救援隊DRONEBIRD計画の詳細を展示します。</p>
<h2 id="-">株式会社ゴーガ</h2>
<p>株式会社ゴーガは、Google Mapsのプレミアパートナーとして、Google Maps API Premium Planの販売及び実装を承っております。 JAPAC Partner of the Yearも受賞した技術力とフットワークでお客様の地図活用を支援いたします。JavaScript, Python, PHPによるウェブシステム、iPhoneアプリ、Androidアプリの開発を得意としています。 そのほか、上記各社の製品販売、OpenStreetMap, MapBox, CARTOなどの活用支援を行なっています。</p>

<h2 id="-">首都大学東京 渡邉英徳研究室</h2>
<p>首都大・渡邉研では，オープンソースのJSライブラリ「Cesium」を用いたデジタルアース・コンテンツを制作しています。これまでに「ヒロシマ・アーカイブ」「震災犠牲者の行動記録」などを発表してきました。本展示では，京都大学東南アジア地域研究研究所，帝国データバンク，佐賀大学医学部との共同研究成果を紹介します。</p>

<h2 id="-">株式会社　ナビタイムジャパン</h2>
<p>ナビタイムジャパンは、ナビタイム・電通・Takramの3社で共同開発した「Round Trip Analyzer」(RTA)を出展します。RTAは、訪日外国人向けアプリ「NAVITIME for Japan Travel」利用者のGPS測位データを元に、訪日外国人旅行者の国内回遊状況を「市区町村間の移動」という単位で描画するインタラクティブなビジュアライザーです。
操作者が直感的・対話的に訪日外国人の移動実態を理解できます。</p>

<h2 id="pacific-spatial-solutions-llc">Pacific Spatial Solutions, LLC</h2>
<p>地理情報の活用には時間がかかる。CARTOがこの問題を解決します。スマートシティ、エリアマネージメント、ビジネスインテリジェンス、オープンデータなら、Pacific Spatial Solutionsにお任せください。そして、もう一つ強力な地図ビジネスツール AvenzaMaps。スマホに地図を取り込んで、オフラインで使えます。さらに、オリジナル地図を世界に向けて販売できます。</p>

<h2 id="-">マルティスープ株式会社</h2>
<p>マルティスープ株式会社は「つくる喜び、つかう喜び」をモットーに、地図と位置・空間情報をつかいお客様の業務を効率化をはかる「iField(アイ・フィールド)」、屋内測位技術を活用したソリューション「iField indoor(アイ・フィールド インドア)]の開発・提供を行っています。本展示では、熊本県立大学での被害調査の活用事例紹介をはじめ、インフラ・工場・倉庫・病院など、様々な“現場”を可視化・効率化の支援を行った事例をご紹介いたします。</p>

<h2 id="-mierune">合同会社MIERUNE</h2>
<p>MIERUNE地図として、OpenStreetMapを独自スタイルで提供しており、<br>
1．低コストでの導入が可能<br>
2．印刷などへの二次利用が可能<br>
3．さまざまなデザインに対応<br>
といった特徴を持っています。<br>
今回のジオ展ではMIERUNE地図の新しいスタイルをご覧いただくとともに、OpenStreetMapやweb地図の活用、地図データの配信についてのご相談を受け付けます。また、MIERUNEは「QGIS」のスポンサーとなっています。QGISの利活用、プラグイン開発についてのご相談も承ります。</p>

<h2 id="life-style-">LIFE STYLE株式会社</h2>
<p>LIFE STYLEは、VRクリエイターエコシステムを展開するベンチャー企業です。
VRクリエイターエコシステムとは、良質なVRコンテンツをより多くのユーザーに届けるためのコミュニティです。具体的には、VRを学ぶ場・VR制作ツール・VRに特化したマッチングサービスを展開しています。VR制作ツールは、360°でその場にいるかのような体験ができるVRコンテンツを、皆様が簡単に制作・活用できる「Flic360Make」サービスとなっております。VRを体験したい方・VRのビジネス活用をお考えの方は、是非ブースまで足をお運びください。</p>

<h2 id="yahoojapan">ヤフー株式会社</h2>
<p>ヤフー株式会社は「ジオ展」に「Yahoo!地図」ならびに「Yahoo!カーナビ」の各ソリューションを出展します。「Yahoo!地図」は、Android版アプリで提供中の地磁気を利用した屋内位置確認技術を展示します。フィンランドの IndoorAtlas（IA）社による屋内測位技術の紹介と、それを用いた屋内空間での課題解決手法を提案します。「Yahoo!カーナビ」は、プローブ情報の活用についてご紹介します。実際にカーナビアプリを使ったユーザーの走行履歴・渋滞情報などを反映したルート探索や実際のデータの一部を公開します。皆さまのご来場をお待ちしております。</p>

'

**Comment by mapconcierge** [comment]
＞ @fumy231 
出展企業の番号順に上記リストを並び替えます！
 
`
<h1 id="-50-">出展企業紹介</h1>

<h2 id="yahoojapan">ヤフー株式会社</h2>
<p>ヤフー株式会社は「ジオ展」に「Yahoo!地図」ならびに「Yahoo!カーナビ」の各ソリューションを出展します。「Yahoo!地図」は、Android版アプリで提供中の地磁気を利用した屋内位置確認技術を展示します。フィンランドの IndoorAtlas（IA）社による屋内測位技術の紹介と、それを用いた屋内空間での課題解決手法を提案します。「Yahoo!カーナビ」は、プローブ情報の活用についてご紹介します。実際にカーナビアプリを使ったユーザーの走行履歴・渋滞情報などを反映したルート探索や実際のデータの一部を公開します。皆さまのご来場をお待ちしております。</p>

<h2 id="-p-">インクリメントP株式会社</h2>
<p>インクリメントP株式会社ではMapFanAPI、MapFanSDKを始めとした地図ソリューション販売を行っております。本展示会には法人向け地図データ製品であるMapFanDBを展示します。
カーナビゲーションにも利用される高精度な道路ネットワークデータを中心にGISシステム向けの様々なコンテンツを紹介します。</p>
<h2 id="-">株式会社ヴァル研究所</h2>
<p>「駅すぱあと路線図」は、様々なデータを駅や路線で集約し活用するニーズに対応するべく、企業や団体が保有するデータやコンテンツと自由に連携できる業界初の全国路線図APIです。 <br>
■特徴<br>
　1.全国の鉄道路線と駅を1枚の路線図で表示、拡大縮小、スクロール可能<br>
　2.スマートフォンでも動作が軽くスムーズな操作感を実現<br>
　3.特定の駅にピンを立てる、路線に色をつけるなど自由な表現が可能<br>
　4.利用者自身が保有するデータ／コンテンツと連携可能<br>
　5.英語版の路線図や駅ナンバリングに対応</p>

<h2 id="-">特定非営利活動法人 クライシスマッパーズ・ジャパン</h2>
<p>大規模災害時にOpenStreetMapを活用して迅速に被災地の地図を作成、現場を後方支援する青山学院大学を本拠地とするボランティア団体です。とくに、発災後の様子をドローンを用いて空から空撮し、迅速に被害状況をマッピングする災害ドローン救援隊DRONEBIRD計画の詳細を展示します。</p>
<h2 id="-">株式会社ゴーガ</h2>
<p>株式会社ゴーガは、Google Mapsのプレミアパートナーとして、Google Maps API Premium Planの販売及び実装を承っております。 JAPAC Partner of the Yearも受賞した技術力とフットワークでお客様の地図活用を支援いたします。JavaScript, Python, PHPによるウェブシステム、iPhoneアプリ、Androidアプリの開発を得意としています。 そのほか、上記各社の製品販売、OpenStreetMap, MapBox, CARTOなどの活用支援を行なっています。</p>

<h2 id="-">首都大学東京 渡邉英徳研究室</h2>
<p>首都大・渡邉研では，オープンソースのJSライブラリ「Cesium」を用いたデジタルアース・コンテンツを制作しています。これまでに「ヒロシマ・アーカイブ」「震災犠牲者の行動記録」などを発表してきました。本展示では，京都大学東南アジア地域研究研究所，帝国データバンク，佐賀大学医学部との共同研究成果を紹介します。</p>

<h2 id="-">株式会社　ナビタイムジャパン</h2>
<p>ナビタイムジャパンは、ナビタイム・電通・Takramの3社で共同開発した「Round Trip Analyzer」(RTA)を出展します。RTAは、訪日外国人向けアプリ「NAVITIME for Japan Travel」利用者のGPS測位データを元に、訪日外国人旅行者の国内回遊状況を「市区町村間の移動」という単位で描画するインタラクティブなビジュアライザーです。
操作者が直感的・対話的に訪日外国人の移動実態を理解できます。</p>

<h2 id="pacific-spatial-solutions-llc">Pacific Spatial Solutions, LLC</h2>
<p>地理情報の活用には時間がかかる。CARTOがこの問題を解決します。スマートシティ、エリアマネージメント、ビジネスインテリジェンス、オープンデータなら、Pacific Spatial Solutionsにお任せください。そして、もう一つ強力な地図ビジネスツール AvenzaMaps。スマホに地図を取り込んで、オフラインで使えます。さらに、オリジナル地図を世界に向けて販売できます。</p>

<h2 id="-">マルティスープ株式会社</h2>
<p>マルティスープ株式会社は「つくる喜び、つかう喜び」をモットーに、地図と位置・空間情報をつかいお客様の業務を効率化をはかる「iField(アイ・フィールド)」、屋内測位技術を活用したソリューション「iField indoor(アイ・フィールド インドア)]の開発・提供を行っています。本展示では、熊本県立大学での被害調査の活用事例紹介をはじめ、インフラ・工場・倉庫・病院など、様々な“現場”を可視化・効率化の支援を行った事例をご紹介いたします。</p>

<h2 id="-mierune">合同会社MIERUNE</h2>
<p>MIERUNE地図として、OpenStreetMapを独自スタイルで提供しており、<br>
1．低コストでの導入が可能<br>
2．印刷などへの二次利用が可能<br>
3．さまざまなデザインに対応<br>
といった特徴を持っています。<br>
今回のジオ展ではMIERUNE地図の新しいスタイルをご覧いただくとともに、OpenStreetMapやweb地図の活用、地図データの配信についてのご相談を受け付けます。また、MIERUNEは「QGIS」のスポンサーとなっています。QGISの利活用、プラグイン開発についてのご相談も承ります。</p>

<h2 id="life-style-">LIFE STYLE株式会社</h2>
<p>LIFE STYLEは、VRクリエイターエコシステムを展開するベンチャー企業です。
VRクリエイターエコシステムとは、良質なVRコンテンツをより多くのユーザーに届けるためのコミュニティです。具体的には、VRを学ぶ場・VR制作ツール・VRに特化したマッチングサービスを展開しています。VR制作ツールは、360°でその場にいるかのような体験ができるVRコンテンツを、皆様が簡単に制作・活用できる「Flic360Make」サービスとなっております。VRを体験したい方・VRのビジネス活用をお考えの方は、是非ブースまで足をお運びください。</p>


`

**Comment by fairlaterfair** [comment]
出展企業の番号順に並び替えと、元ページに追加された企業情報追加します。
`
<h1 id="-50-">出展企業紹介</h1>

<h2 id="yahoojapan">ヤフー株式会社</h2>
<p>ヤフー株式会社は「ジオ展」に「Yahoo!地図」ならびに「Yahoo!カーナビ」の各ソリューションを出展します。「Yahoo!地図」は、Android版アプリで提供中の地磁気を利用した屋内位置確認技術を展示します。フィンランドの IndoorAtlas（IA）社による屋内測位技術の紹介と、それを用いた屋内空間での課題解決手法を提案します。「Yahoo!カーナビ」は、プローブ情報の活用についてご紹介します。実際にカーナビアプリを使ったユーザーの走行履歴・渋滞情報などを反映したルート探索や実際のデータの一部を公開します。皆さまのご来場をお待ちしております。</p>

<h2 id="-">株式会社ヴァル研究所</h2>
<p>「駅すぱあと路線図」は、様々なデータを駅や路線で集約し活用するニーズに対応するべく、企業や団体が保有するデータやコンテンツと自由に連携できる業界初の全国路線図APIです。 <br>
■特徴<br>
　1.全国の鉄道路線と駅を1枚の路線図で表示、拡大縮小、スクロール可能<br>
　2.スマートフォンでも動作が軽くスムーズな操作感を実現<br>
　3.特定の駅にピンを立てる、路線に色をつけるなど自由な表現が可能<br>
　4.利用者自身が保有するデータ／コンテンツと連携可能<br>
　5.英語版の路線図や駅ナンバリングに対応</p>

<h2 id="-p-">インクリメントP株式会社</h2>
<p>インクリメントP株式会社ではMapFanAPI、MapFanSDKを始めとした地図ソリューション販売を行っております。本展示会には法人向け地図データ製品であるMapFanDBを展示します。
カーナビゲーションにも利用される高精度な道路ネットワークデータを中心にGISシステム向けの様々なコンテンツを紹介します。</p>

<h2 id="-mierune">合同会社MIERUNE</h2>
<p>MIERUNE地図として、OpenStreetMapを独自スタイルで提供しており、<br>
1．低コストでの導入が可能<br>
2．印刷などへの二次利用が可能<br>
3．さまざまなデザインに対応<br>
といった特徴を持っています。<br>
今回のジオ展ではMIERUNE地図の新しいスタイルをご覧いただくとともに、OpenStreetMapやweb地図の活用、地図データの配信についてのご相談を受け付けます。また、MIERUNEは「QGIS」のスポンサーとなっています。QGISの利活用、プラグイン開発についてのご相談も承ります。</p>

<h2 id="-">株式会社　ナビタイムジャパン</h2>
<p>ナビタイムジャパンは、ナビタイム・電通・Takramの3社で共同開発した「Round Trip Analyzer」(RTA)を出展します。RTAは、訪日外国人向けアプリ「NAVITIME for Japan Travel」利用者のGPS測位データを元に、訪日外国人旅行者の国内回遊状況を「市区町村間の移動」という単位で描画するインタラクティブなビジュアライザーです。
操作者が直感的・対話的に訪日外国人の移動実態を理解できます。</p>

<h2 id="pacific-spatial-solutions-llc">Pacific Spatial Solutions, LLC</h2>
<p>地理情報の活用には時間がかかる。CARTOがこの問題を解決します。スマートシティ、エリアマネージメント、ビジネスインテリジェンス、オープンデータなら、Pacific Spatial Solutionsにお任せください。そして、もう一つ強力な地図ビジネスツール AvenzaMaps。スマホに地図を取り込んで、オフラインで使えます。さらに、オリジナル地図を世界に向けて販売できます。</p>

<h2 id="pacific-spatial-solutions-llc">株式会社コミュニケーション・プランニング</h2>
<p>株式会社コミュニケーション・プランニングは、3DCGコンテンツのVR化や、 位置情報を活用したARシステムの開発等を支援します。 
企画から制作・開発、機器調達、導入支援まで幅広く対応可能です。 
今回のジオ展ではハイクオリティ＆マルチデバイスVRを体験していただきます。
また、タブレットとARの組み合わせ事例、モバイルネイティブのGISエンジン 「GIcompo for Android」「GIcompo for iOS」も併せて展示します。</p>

<h2 id="-">マルティスープ株式会社</h2>
<p>マルティスープ株式会社は「つくる喜び、つかう喜び」をモットーに、地図と位置・空間情報をつかいお客様の業務を効率化をはかる「iField(アイ・フィールド)」、屋内測位技術を活用したソリューション「iField indoor(アイ・フィールド インドア)]の開発・提供を行っています。本展示では、熊本県立大学での被害調査の活用事例紹介をはじめ、インフラ・工場・倉庫・病院など、様々な“現場”を可視化・効率化の支援を行った事例をご紹介いたします。</p>

<h2 id="life-style-">LIFE STYLE株式会社</h2>
<p>LIFE STYLEは、VRクリエイターエコシステムを展開するベンチャー企業です。
VRクリエイターエコシステムとは、良質なVRコンテンツをより多くのユーザーに届けるためのコミュニティです。具体的には、VRを学ぶ場・VR制作ツール・VRに特化したマッチングサービスを展開しています。VR制作ツールは、360°でその場にいるかのような体験ができるVRコンテンツを、皆様が簡単に制作・活用できる「Flic360Make」サービスとなっております。VRを体験したい方・VRのビジネス活用をお考えの方は、是非ブースまで足をお運びください。</p>

<h2 id="-">特定非営利活動法人 クライシスマッパーズ・ジャパン</h2>
<p>大規模災害時にOpenStreetMapを活用して迅速に被災地の地図を作成、現場を後方支援する青山学院大学を本拠地とするボランティア団体です。とくに、発災後の様子をドローンを用いて空から空撮し、迅速に被害状況をマッピングする災害ドローン救援隊DRONEBIRD計画の詳細を展示します。</p>

<h2 id="-">首都大学東京 渡邉英徳研究室</h2>
<p>首都大・渡邉研では，オープンソースのJSライブラリ「Cesium」を用いたデジタルアース・コンテンツを制作しています。これまでに「ヒロシマ・アーカイブ」「震災犠牲者の行動記録」などを発表してきました。本展示では，京都大学東南アジア地域研究研究所，帝国データバンク，佐賀大学医学部との共同研究成果を紹介します。</p>

<h2 id="-">株式会社ゴーガ</h2>
<p>株式会社ゴーガは、Google Mapsのプレミアパートナーとして、Google Maps API Premium Planの販売及び実装を承っております。 JAPAC Partner of the Yearも受賞した技術力とフットワークでお客様の地図活用を支援いたします。JavaScript, Python, PHPによるウェブシステム、iPhoneアプリ、Androidアプリの開発を得意としています。 そのほか、上記各社の製品販売、OpenStreetMap, MapBox, CARTOなどの活用支援を行なっています。</p>


`

**Comment by mapconcierge** [comment]
とりあえず、出展番号順に並び替えて  Program ページに反映済みです。残る別ページ化は今日中に対応予定です。
http://geoten.org/program.html
