### ISSUE TITLE
地図のフルスクリーン表示

### ISSUE THREAD

**Issue by fumy231** [mapconcierge/www_geoten#2]
ロンドンパリあたりに飛びます。東京にしましょう。

https://umap.openstreetmap.fr/ja/map/2017_138287#6/51.000/2.000

**Comment by mapconcierge** [comment]
URL修正しました！

`<a href="https://umap.openstreetmap.fr/ja/map/2017_138287?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false#16/35.6799/139.7363">フルスクリーン表示</a>`
