### ISSUE TITLE
リンクページを作って紹介記事などへリンクしてください

### ISSUE THREAD

**Issue by fumy231** [mapconcierge/www_geoten#3]
Linkタブが欲しいです。
紹介記事にリンクが欲しいです。

ジオ展2017
http://internet.watch.impress.co.jp/docs/column/chizu/1055371.html
http://www.yomiuri.co.jp/adv/life/release/detail/00039424.html

ジオ展2016
http://internet.watch.impress.co.jp/docs/column/chizu/1026451.html

**Comment by mapconcierge** [comment]
links ページ追加しました！
http://geoten.org/links.html
